diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=schannel
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.email=aryanshrestha000005@gmail.com
user.name=idulife
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.upstream.url=https://github.com/idunlife/god_save_the_biscuit.git
remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
branch.main.remote=origin
branch.main.vscode-merge-base=origin/main
branch.main.merge=refs/heads/main
remote.origin.url=https://github.com/idunlife/god_save_the_biscuit.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
